# Generated by Django 3.2.8 on 2021-10-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
