# Generated by Django 3.2.8 on 2021-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_App', '0002_rename_user_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
    ]
